[package]
name = "beatmedaddy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.25"
tungstenite = "0.16.0"
url = "2.2.2"
